name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Ensure ESLint binary has executable permissions
        run: chmod +x ./node_modules/.bin/eslint

      - name: Linting
        run: npm run lint

      

      - name: Build Docker image
        run: docker build -t abdulrahman101/node-hello-world .

      - name: Push Docker image to registry
        uses: docker/login-action@v1
        with:
          username: abdulrahman101
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push abdulrahman101/node-hello-world
